### ISSUE TITLE
UIRefreshControl not centered in iPhone 6

### ISSUE THREAD

**Issue by marcllucia** [bdbergeron/BDBSpinKitRefreshControl#5] opened 2014-11-04 23:31 UTC
If you test the library in an iPhone 6 the refresh control is not in the center of the table view

**Comment by bdbergeron** [comment] 2014-11-05 03:23
Is this a duplicate of issue #4? I've tested it on an iPhone 6/6+, and it's working for me. I need more information in order to reproduce what you're seeing. Can you attach a screenshot?

**Comment by marcllucia** [comment] 2014-11-05 17:51
I think that the problem is that I'm not using an UITableViewController, I'm adding the refresh control as a subview of the table as descibred here: http://stackoverflow.com/questions/10291537/pull-to-refresh-uitableview-without-uitableviewcontroller

Could this be the problem?

**Comment by bdbergeron** [comment] 2014-11-05 17:54
Oh, interesting. I never thought about this use case. It could very well be the problem. Let me investigate a bit more. Are you doing your layouts programmatically or with a storyboard/xib?

**Comment by marcllucia** [comment] 2014-11-05 17:55
I'm using storyboard and autolayout but I'm adding the refresh control to the UITableView programmatically, it worked perfectly until the new iPhone 6 and 6 plus were introduced.

**Comment by bdbergeron** [comment] 2014-11-05 18:41
In BDBSpinKitRefreshControl.m, right after `_spinner` is instantiated on line 57, try adding this:

`_spinner.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleRightMargin;`

That seems to take care of it for me in the little demo app I just whipped together. If it works for you, I'll push a new version with this fix.

**Comment by bdbergeron** [comment] 2014-11-05 19:05
I think the issue comes from the use of size classes in Xcode. When the view hierarchy is initially inflated from the storyboard/xib, it uses the default size class width and height to layout elements. When the view is about to be displayed, another pass through the view hierarchy is made by layoutIfNeeded/viewWillLayoutSubviews, which then updates any AutoLayout constraints to their correct placements and values according to the device's screen. Because I'm inserting and centering the spinner in a call to viewDidMoveToSubview (which is performed upon initial view hierarchy creation), the centering never updates when the superview's width changes. Definitely an oversight on my part.

**Comment by marcllucia** [comment] 2014-11-05 22:32
Adding the line

`_spinner.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleRightMargin;``

solved the issue!

**Comment by bdbergeron** [comment] 2014-11-05 22:35
Great! I'll push a new patch version with that fix when I get home!

**Comment by marcllucia** [comment] 2014-11-05 22:36
Perfect! will you upgrade the cocoapods version too?

**Comment by bdbergeron** [comment] 2014-11-05 22:37
Yup!

**Closed as completed** 2014-11-05 22:37 UTC

**Comment by bdbergeron** [comment] 2014-11-05 23:35
New version pushed to CocoaPods
